# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc_image_streaming.proto import image_stream_pb2 as grpc__image__streaming_dot_proto_dot_image__stream__pb2


class ImageStreamerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamFrames = channel.stream_stream(
                '/image_streaming.ImageStreamer/StreamFrames',
                request_serializer=grpc__image__streaming_dot_proto_dot_image__stream__pb2.ImageFrame.SerializeToString,
                response_deserializer=grpc__image__streaming_dot_proto_dot_image__stream__pb2.ServerResponse.FromString,
                )


class ImageStreamerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamFrames(self, request_iterator, context):
        """Bidirectional streaming RPC for sending image frames
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageStreamerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamFrames': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamFrames,
                    request_deserializer=grpc__image__streaming_dot_proto_dot_image__stream__pb2.ImageFrame.FromString,
                    response_serializer=grpc__image__streaming_dot_proto_dot_image__stream__pb2.ServerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'image_streaming.ImageStreamer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageStreamer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamFrames(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/image_streaming.ImageStreamer/StreamFrames',
            grpc__image__streaming_dot_proto_dot_image__stream__pb2.ImageFrame.SerializeToString,
            grpc__image__streaming_dot_proto_dot_image__stream__pb2.ServerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
