# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_image_streaming/proto/image_stream.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-grpc_image_streaming/proto/image_stream.proto\x12\x0fimage_streaming\"F\n\nImageFrame\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x11\n\tcamera_id\x18\x03 \x01(\t\"v\n\x0eServerResponse\x12\x36\n\x06status\x18\x01 \x01(\x0e\x32&.image_streaming.ServerResponse.Status\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1b\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x32\x63\n\rImageStreamer\x12R\n\x0cStreamFrames\x12\x1b.image_streaming.ImageFrame\x1a\x1f.image_streaming.ServerResponse\"\x00(\x01\x30\x01\x62\x06proto3')



_IMAGEFRAME = DESCRIPTOR.message_types_by_name['ImageFrame']
_SERVERRESPONSE = DESCRIPTOR.message_types_by_name['ServerResponse']
_SERVERRESPONSE_STATUS = _SERVERRESPONSE.enum_types_by_name['Status']
ImageFrame = _reflection.GeneratedProtocolMessageType('ImageFrame', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEFRAME,
  '__module__' : 'grpc_image_streaming.proto.image_stream_pb2'
  # @@protoc_insertion_point(class_scope:image_streaming.ImageFrame)
  })
_sym_db.RegisterMessage(ImageFrame)

ServerResponse = _reflection.GeneratedProtocolMessageType('ServerResponse', (_message.Message,), {
  'DESCRIPTOR' : _SERVERRESPONSE,
  '__module__' : 'grpc_image_streaming.proto.image_stream_pb2'
  # @@protoc_insertion_point(class_scope:image_streaming.ServerResponse)
  })
_sym_db.RegisterMessage(ServerResponse)

_IMAGESTREAMER = DESCRIPTOR.services_by_name['ImageStreamer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGEFRAME._serialized_start=66
  _IMAGEFRAME._serialized_end=136
  _SERVERRESPONSE._serialized_start=138
  _SERVERRESPONSE._serialized_end=256
  _SERVERRESPONSE_STATUS._serialized_start=229
  _SERVERRESPONSE_STATUS._serialized_end=256
  _IMAGESTREAMER._serialized_start=258
  _IMAGESTREAMER._serialized_end=357
# @@protoc_insertion_point(module_scope)
